name: Release PyPI Wheel

# on: [push, pull_request]
on:
  push:
    branches:
      - main
      - shared_thread_pool
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    container: trinkle23897/envpool-release:2023-01-02-5f1a5fd
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        run: |
          ln -sf /root/.cache $HOME/.cache
          ln -sf /root/.pyenv $HOME/.pyenv
          pyenv global ${{ matrix.python-version }}-dev
      - name: Build
        run: |
          make pypi-wheel
          pip3 install dist/*.whl --force-reinstall
      - name: Test
        run: |
          make release-test
      - name: Upload artifact
        uses: actions/upload-artifact@main
        with:
          name: wheel
          path: wheelhouse/
